document.addEventListener('DOMContentLoaded', () => {

        // --- CONFIG & GAME STATE ---
            const GRID_SIZE = 10;
                const INITIAL_STATS = {
                        hull: 100,
                                maxHull: 100,
                                        fuel: 100,
                                                maxFuel: 100,
                                                        credits: 50,
                                                                weapons: 1, // Base damage
                                                                    };

                                                                        let gameState = {};

                                                                            // --- DOM ELEMENTS ---
                                                                                const mapGrid = document.getElementById('galaxy-map');
                                                                                    const logEntries = document.getElementById('log-entries');
                                                                                        
                                                                                            // Status panel
                                                                                                const hullBar = document.getElementById('hull-bar');
                                                                                                    const hullValue = document.getElementById('hull-value');
                                                                                                        const fuelBar = document.getElementById('fuel-bar');
                                                                                                            const fuelValue = document.getElementById('fuel-value');
                                                                                                                const creditsValue = document.getElementById('credits-value');
                                                                                                                    const weaponsValue = document.getElementById('weapons-value');
                                                                                                                        
                                                                                                                            // Modal
                                                                                                                                const modalBackdrop = document.getElementById('modal-backdrop');
                                                                                                                                    const modalTitle = document.getElementById('modal-title');
                                                                                                                                        const modalText = document.getElementById('modal-text');
                                                                                                                                            const modalChoices = document.getElementById('modal-choices');

                                                                                                                                                // --- GAME LOGIC ---

                                                                                                                                                    function initGame() {
                                                                                                                                                            // Reset player state
                                                                                                                                                                    gameState.player = {
                                                                                                                                                                                ...INITIAL_STATS,
                                                                                                                                                                                            x: 0,
                                                                                                                                                                                                        y: 0,
                                                                                                                                                                                                                };
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                gameState.gameOver = false;
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                // Generate map
                                                                                                                                                                                                                                                        generateMap();

                                                                                                                                                                                                                                                                // Initial render
                                                                                                                                                                                                                                                                        renderMap();
                                                                                                                                                                                                                                                                                renderStatus();
                                                                                                                                                                                                                                                                                        addToLog("Welcome, Cosmic Courier. Your mission awaits.");
                                                                                                                                                                                                                                                                                                addToLog(`You start at sector [${gameState.player.x}, ${gameState.player.y}].`);
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                        function generateMap() {
                                                                                                                                                                                                                                                                                                                gameState.map = [];
                                                                                                                                                                                                                                                                                                                        for (let y = 0; y < GRID_SIZE; y++) {
                                                                                                                                                                                                                                                                                                                                    const row = [];
                                                                                                                                                                                                                                                                                                                                                for (let x = 0; x < GRID_SIZE; x++) {
                                                                                                                                                                                                                                                                                                                                                                row.push({
                                                                                                                                                                                                                                                                                                                                                                                    visited: false,
                                                                                                                                                                                                                                                                                                                                                                                                        event: generateEvent(x, y),
                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                gameState.map.push(row);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Set start and destination
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gameState.startPos = { x: 0, y: 0 };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gameState.map[0][0].event = 'START';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gameState.map[0][0].visited = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Place destination in the opposite corner
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gameState.destPos = { x: GRID_SIZE - 1, y: GRID_SIZE - 1 };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gameState.map[GRID_SIZE - 1][GRID_SIZE - 1].event = 'DESTINATION';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function generateEvent(x, y) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Avoid events too close to start
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (Math.abs(x - gameState.startPos.x) < 2 && Math.abs(y - gameState.startPos.y) < 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return 'EMPTY';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const rand = Math.random();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (rand < 0.15) return 'PIRATE';      // 15% chance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (rand < 0.35) return 'FUEL_CACHE';  // 20% chance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (rand < 0.45) return 'ASTEROID';    // 10% chance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (rand < 0.55) return 'STATION';     // 10% chance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (rand < 0.65) return 'DERELICT';    // 10% chance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return 'EMPTY';                        // 30% chance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function movePlayer(dx, dy) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (gameState.gameOver) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const newX = gameState.player.x + dx;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const newY = gameState.player.y + dy;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Boundary checks
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (newX < 0 || newX >= GRID_SIZE || newY < 0 || newY >= GRID_SIZE) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                addToLog("Cannot travel beyond the edge of the galaxy.", 'error');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Fuel check
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const fuelCost = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (gameState.player.fuel < fuelCost) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        addToLog("Not enough fuel to travel!", 'error');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gameState.player.fuel -= fuelCost;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gameState.player.x = newX;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gameState.player.y = newY;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gameState.map[newY][newX].visited = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            addToLog(`Traveled to sector [${newX}, ${newY}]. Fuel remaining: ${gameState.player.fuel}.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            renderAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    triggerEvent(newX, newY);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            checkGameOver();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function triggerEvent(x, y) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const eventType = gameState.map[y][x].event;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Prevent re-triggering events on visited special sectors
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (eventType === 'START' || eventType === 'DESTINATION') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // do nothing special, just log arrival
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Mark event as done so it doesn't re-trigger
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       gameState.map[y][x].event = 'EMPTY';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       switch(eventType) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   case 'START':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   addToLog("You are at the starting point.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               case 'DESTINATION':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               winGame();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           case 'FUEL_CACHE':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const foundFuel = Math.floor(Math.random() * 20) + 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           gameState.player.fuel = Math.min(gameState.player.maxFuel, gameState.player.fuel + foundFuel);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           addToLog(`You found a fuel cache! Recovered ${foundFuel} fuel.`, 'success');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       case 'ASTEROID':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
})